name: messier42_createANN&OLS

services:
  activationBase:
    image: haaniansari/activationbase_messier42
    #also available at {add the link to your docker repo}
    volumes:
      - type: bind
        source: ./ai_system
        target: /tmp/ai_system
    command: cp -r /tmp/activationBase /tmp/ai_system/

  learningBase:
    image: haaniansari/learningbase_messier42
    #also available at {add the link to your docker repo}
    volumes:
      - type: bind
        source: ./ai_system
        target: /tmp/ai_system
    command: cp -r /tmp/learningBase /tmp/ai_system/

  codeBase:
    image: droyyy/codebase_messier42
    #also available at {add the link to your docker repo}
    volumes:
      - type: bind
        source: ./ai_system
        target: /tmp/ai_system
    command: bash -c "python3 /tmp/codeBase/ann_model/hybridModel.py && python3 /tmp/codeBase/ols_model/OLS_model.py" 

volumes:
  myvol:
