name: messier42_applyANNSolution

services:
  activationBase:
    image: activationbase
    volumes:
      - type: bind
        source: ./ai_system
        target: /tmp/ai_system
    command: cp -r /tmp/activationBase /tmp/ai_system/

  knowledgeBase:
    image: knowledgebase
    volumes:
      - type: bind
        source: ./ai_system
        target: /tmp/ai_system
    command: cp -r /tmp/knowledgeBase /tmp/ai_system/

  codeBase:
    image: codebase
    volumes:
      - type: bind
        source: ./ai_system
        target: /tmp/ai_system
    command: bash -c "python3 /tmp/codeBase/activateANN.py" 

volumes:
  myvol: